[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PMS"
authors = [{name = "Dip sarkar", email = "santu.koffeekodes@gmail.com"}]
dynamic = ["1.0", "PMS docs"]
